### ISSUE TITLE
release 0.4.4

### ISSUE THREAD

**Issue by viktorkertesz** [jiujing/nornir_table_inventory#2]
Dear @jiujing ,
May I ask you to bump version at https://github.com/jiujing/nornir_table_inventory/blob/4e9565df0dc1769e99c47f16a3d75b26653263b7/pyproject.toml#L3
and create a release on [PyPi](https://pypi.org/project/nornir-table-inventory/)?

I'm using the git latest version and it'd be more convenient to deploy stuff from PyPi.

Thanks!

**Comment by jiujing** [comment]
You can use it in pypi with version 0.4.4. I am afraid of that, the changes conflic with user‘s existed codes. I
 have released version 0.4.4 .

**Comment by viktorkertesz** [comment]
I don't understand you. I cannot see newer version than 0.4.3 in PyPi.
![image](https://user-images.githubusercontent.com/74217042/223111219-eb170e11-4b68-4067-b88a-0b3d9c3292d3.png)

Actually the latest version broke my codes, so I had to choose between freeze older version or try to make it better. I wanted to contribute because I like the idea of using excel/csv and leverage this project already. In release notes you may mention that if the old code breaks, use specific old code. Other devs usually choose to change at least minor version number to indicate bigger changes. Like it could be v0.5.0.

**Comment by jiujing** [comment]
> I don't understand you. I cannot see newer version than 0.4.3 in PyPi. ![image](https://user-images.githubusercontent.com/74217042/223111219-eb170e11-4b68-4067-b88a-0b3d9c3292d3.png)
> 
> Actually the latest version broke my codes, so I had to choose between freeze older version or try to make it better. I wanted to contribute because I like the idea of using excel/csv and leverage this project already. In release notes you may mention that if the old code breaks, use specific old code. Other devs usually choose to change at least minor version number to indicate bigger changes. Like it could be v0.5.0.

I am sorry for my mistakes. I removed version 0.4.4 and  tried to republish version 0.4.4 but failed. I found the problem,but can not republish a version with same name . I have no choice but publish version 0.4.5 . So sorry. 
You can install version 0.4.5 .
